name: Testes com Appium + Emulador Android

on:
  workflow_dispatch:
  push:
    paths:
      - 'artifacts/**'
      - 'tests/**'
      - '.github/workflows/**'
      - 'package.json'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Descompactar APK
        run: unzip -o artifacts/MauiTecmicProject.zip -d artifacts/

      - name: Configurar Java e Android SDK + Emulador
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          script: |
            echo "Iniciar emulador Android"
            adb devices
            adb install artifacts/MauiTecmicProject.apk
            adb shell input keyevent 82

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar Appium e dependências JS
        run: |
          npm ci || npm install
          npm install -g appium
          appium driver install uiautomator2

      - name: Iniciar Appium em background
        run: |
          nohup appium --log-level error &
          sleep 10

      - name: Verificar APK instalado
        run: adb shell pm list packages | grep com.companyname.mauitecmicproject

      - name: Executar testes com WebDriverIO
        run: npm tests/test


